name: Update index from PDFs

on:
  push:
    paths:
      - 'pdf/**'
      - 'generate_index.py'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run generator
        run: python generate_index.py

      - name: Commit changes
        run: |
          git config user.name "auto-bot"
          git config user.email "auto@github"
          git add index.html
          git commit -m "Auto update PDF list" || echo "No changes"
          git push
